name: Run JUnit CI

#triger/kapan action jalan
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  automation:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run All Runner
        run: gradlew clean test --tests runner.ApiRunner

      - name: Run API Runner
        run: gradlew clean test --tests runner.ApiRunner

      - name: Run Web Runner
        run: gradlew clean test --tests runner.ApiRunner

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cucumber-reports
          path: reports/